-- Shareable activity rooms and commit arrival ETA.
-- Existing local rows keep NULL codes; all newly created activities get a
-- 4-letter uppercase code generated by the Worker.

ALTER TABLE activities ADD COLUMN code TEXT;
CREATE UNIQUE INDEX idx_activities_code ON activities (code);

ALTER TABLE participations ADD COLUMN arrival_at INTEGER;
