import { useEffect, useState } from 'react'
import { policyDocs } from '../policy/engine'
import { MarkdownBlock } from './MarkdownBlock'

interface Props {
  onClose: () => void
  /** Optional heading; omit when the surrounding surface already titles it. */
  title?: string
}

/** The policy-language reference modal, shared by the math sandbox and the
 * home notification-policy panel. Loads the docs (generated by the WASM
 * engine) on mount and renders them as Markdown. */
export function PolicyHelp({ onClose, title }: Props) {
  const [helpText, setHelpText] = useState('Loading documentation…')

  useEffect(() => {
    let cancelled = false
    void policyDocs().then((text) => {
      if (!cancelled) setHelpText(text)
    })
    return () => {
      cancelled = true
    }
  }, [])

  return (
    <div
      className="math-help-backdrop"
      onClick={(e) => {
        e.stopPropagation()
        onClose()
      }}
    >
      <section className="math-help-panel" onClick={(e) => e.stopPropagation()}>
        <header className="math-help-head">
          {title ? <h2>{title}</h2> : <span />}
          <button type="button" onClick={onClose} title="Close help" aria-label="Close help">
            <span className="noto-emoji" aria-hidden="true">✖️</span>
          </button>
        </header>
        <MarkdownBlock className="math-help-markdown" source={helpText} />
      </section>
    </div>
  )
}
